// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt1MVEjYBBb36rEFBEHHcBDmjxP1V1k0g',
    appId: '1:754331805057:web:7062c9658dd79db88db480',
    messagingSenderId: '754331805057',
    projectId: 'smart-library-seating-system',
    authDomain: 'smart-library-seating-system.firebaseapp.com',
    storageBucket: 'smart-library-seating-system.firebasestorage.app',
    measurementId: 'G-RT6L6C564R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3mUIsFkH6psI28s0oSB3DB5iKRdfHdMg',
    appId: '1:754331805057:android:89d1b1d1b2e09f828db480',
    messagingSenderId: '754331805057',
    projectId: 'smart-library-seating-system',
    storageBucket: 'smart-library-seating-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxbgxTkpKboQEhvPLaMvvc3G5fBZHlkcI',
    appId: '1:754331805057:ios:25758bea4999a4de8db480',
    messagingSenderId: '754331805057',
    projectId: 'smart-library-seating-system',
    storageBucket: 'smart-library-seating-system.firebasestorage.app',
    iosBundleId: 'com.example.libseat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxbgxTkpKboQEhvPLaMvvc3G5fBZHlkcI',
    appId: '1:754331805057:ios:25758bea4999a4de8db480',
    messagingSenderId: '754331805057',
    projectId: 'smart-library-seating-system',
    storageBucket: 'smart-library-seating-system.firebasestorage.app',
    iosBundleId: 'com.example.libseat2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt1MVEjYBBb36rEFBEHHcBDmjxP1V1k0g',
    appId: '1:754331805057:web:a48001fb1d3a70368db480',
    messagingSenderId: '754331805057',
    projectId: 'smart-library-seating-system',
    authDomain: 'smart-library-seating-system.firebaseapp.com',
    storageBucket: 'smart-library-seating-system.firebasestorage.app',
    measurementId: 'G-0Y860GTDPZ',
  );
}
